name: AI Sync

on:
  push:
    branches: [ main ]
    paths:
      - "data/**"
      - "schema/**"
      - "src/**"
      - "pyproject.toml"
      - "requirements.txt"
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"  # รันทุก 6 ชั่วโมง

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure secrets
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}
          WEB3STORAGE_TOKEN: ${{ secrets.WEB3STORAGE_TOKEN }}
        run: |
          cp .env.example .env
          sed -i "s|PINATA_JWT=.*|PINATA_JWT=${PINATA_JWT}|" .env || true
          sed -i "s|WEB3STORAGE_TOKEN=.*|WEB3STORAGE_TOKEN=${WEB3STORAGE_TOKEN}|" .env || true

      - name: Run AI Sync
        run: |
          python -m src.mf_sync.sync --collections seed-of-hope ducks-of-hope --push

      - name: Commit generated artifacts
        run: |
          git config user.name "mmfarm-bot"
          git config user.email "bot@mameefarm.local"
          git add manifests/ verifications/ build/
          git commit -m "chore(sync): update manifests, proofs, embeddings" || echo "No changes"
          git push
